# Generated by Django 3.1.4 on 2021-02-05 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photography', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pic',
            name='pic_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
