# Generated by Django 3.1.4 on 2021-02-06 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photography', '0003_messages'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Messages',
            new_name='Message',
        ),
    ]
