# Generated by Django 3.1.4 on 2021-02-06 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photography', '0004_auto_20210206_2004'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
