# Generated by Django 3.1.4 on 2021-02-07 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photography', '0005_delete_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(blank=True, max_length=10)),
                ('email', models.EmailField(blank=True, max_length=15)),
                ('content', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
